package com.example.demo.dao;

import com.example.demo.bean.User;
import com.example.demo.bean.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    List<User> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated Mon Nov 18 17:26:16 CST 2019
     */
    int updateByPrimaryKey(User record);
}